#!/usr/bin/env python3
"""Generate a review-first About-field reconciliation from the public lineage."""
import json
import shlex
import sys
from validate import LINEAGE,parse
PREAMBLE='''#!/usr/bin/env bash
# Generated by lineage/render.py. Default is a plan; --apply performs the edits.
set -euo pipefail
apply=false
if [[ "${1:-}" == "--apply" ]]; then apply=true
elif [[ $# -gt 0 ]]; then printf 'usage: %s [--apply]\\n' "$0"; exit 2; fi

reconcile() {
  local repo="$1" description="$2" topics="$3" payload="$4" current_desc current_topics state
  state="$(gh api "repos/$repo" --jq '[.visibility, (.archived|tostring)] | join(" ")')"
  if [[ "$state" != 'public false' ]]; then
    printf 'skip %s: visibility/archive state changed (%s)\\n' "$repo" "$state"
    return
  fi
  current_desc="$(gh repo view "$repo" --json description --jq '.description // ""')"
  current_topics="$(gh api "repos/$repo/topics" --jq '.names | sort | join(" ")')"
  if [[ "$current_desc" != "$description" ]]; then
    printf '%s description: %s -> %s\\n' "$repo" "$current_desc" "$description"
    if $apply; then gh repo edit "$repo" --description "$description"; fi
  fi
  if [[ "$current_topics" != "$topics" ]]; then
    printf '%s topics: %s -> %s\\n' "$repo" "$current_topics" "$topics"
    if $apply; then gh api --method PUT "repos/$repo/topics" --input - <<< "$payload" >/dev/null; fi
  fi
}
'''
def blocks():
    nodes,_=parse(LINEAGE.read_text());runnable=[];archived=[]
    for name,node in sorted(nodes.items()):
        topics=sorted(set(node['topics'].split()))
        command='reconcile '+' '.join(shlex.quote(v) for v in [node['repo'],node['claim'],' '.join(topics),json.dumps({'names':topics})])
        (archived if node['github_archived'] else runnable).append(command)
    return runnable,archived

def main():
    runnable,archived=blocks()
    if '--check' in sys.argv:
        print(f'{len(runnable)} metadata plans; {len(archived)} archived repositories skipped. No writes.');return 0
    print(PREAMBLE)
    print('\n'.join(runnable))
    print('\n# Archived at the recorded observation; do not unarchive from this projection.')
    print('\n'.join('# '+line for line in archived))
    return 0
if __name__=='__main__':raise SystemExit(main())
