#!/usr/bin/env python3
"""Project profile prose and the public lineage into a reproducible README."""
from __future__ import annotations
import html
import sys
from pathlib import Path
from validate import LINEAGE, parse
VOICE = LINEAGE.parent / 'profile-voice.md'
LINES = [('substrate','Records and execution'), ('surface','Editing and communication'),
         ('instrument','Inspection and guidance'), ('method','Working methods'),
         ('world','Generative worlds'), ('reference','Research and references')]

def esc(text):
    return html.escape(str(text)).replace('|','&#124;').replace('\n',' ')

def link(node): return f"[{node['repo'].split('/')[1]}](https://github.com/{node['repo']})"

def source_link(node):
    ev=node['evidence']
    return f"[{ev['revision'][:8]}:{ev['path']}](https://github.com/{node['repo']}/blob/{ev['revision']}/{ev['path']})"

def diagram(nodes, edges):
    shown=[e for e in edges if e['state']!='unsupported']
    if not shown: return ''
    ids={name:f'n{i}' for i,name in enumerate(nodes)}
    touched={e[end] for e in shown for end in ['from','to']}
    lines=['```mermaid','flowchart TD']
    for name in nodes:
        if name in touched: lines.append(f'  {ids[name]}["{esc(nodes[name]["repo"].split("/")[1])}"]')
    for e in shown:
        arrow='-->' if e['state']=='documented' else '-.->'
        label=esc(e['type']+' / '+e['state'])
        lines.append(f'  {ids[e["from"]]} {arrow}|"{label}"| {ids[e["to"]]}')
    return '\n'.join(lines+['```'])

def page(nodes,edges):
    lines=['<!-- Generated by lineage/render.py. Edit lineage.yaml or profile-voice.md. -->','',VOICE.read_text().strip(),'']
    lines+=['## Relations','',diagram(nodes,edges),'',
            'Solid links are documented relations. Dotted links are reported declarations or explicit inferences. Unsupported claims stay in [LINEAGE.md](LINEAGE.md) and are excluded from this graph. Optional provision does not mean a running dependency.','']
    for kind,title in LINES:
        group=[n for n in nodes.values() if n['line']==kind]
        if not group: continue
        lines += ['## '+title,'','| Repository | Purpose | State | Source |','| --- | --- | --- | --- |']
        for n in group:
            state=n['status'] + ('; GitHub archived' if n['github_archived'] else '')
            if n['fork']: state+='; fork'
            lines.append(f"| {link(n)} | {esc(n['claim'])} | {esc(state)} | {source_link(n)} |")
        lines.append('')
    lines += ['## Reproduce the record','',
              'Run these in the `system-cartographer` checkout containing `lineage/`:','',
              '```sh','python -m pip install -r lineage/requirements.txt','python lineage/validate.py',
              'python lineage/verify_sources.py --remote','python lineage/render.py --check',
              'python -m unittest discover -s lineage/tests -v','```','',
              'The [full map](LINEAGE.md) contains each observed source command and result, evidence limits, and earlier reported test results. The [Schematically document](lineage.sov) is another generated view of the same record.','']
    return '\n'.join(lines)

def main():
    nodes,edges=parse(LINEAGE.read_text())
    text=page(nodes,edges)
    if '--selfcheck' in sys.argv or '--check' in sys.argv:
        for n in nodes.values():
            if link(n) not in text: raise ValueError('missing node '+n['repo'])
        print(f'PASS: {len(nodes)} nodes projected; source evidence explicitly scoped.'); return 0
    print(text,end=''); return 0
if __name__=='__main__': raise SystemExit(main())
