#!/usr/bin/env python3
"""Generate every lineage view, or refuse drift without changing any file."""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
from pathlib import Path
from validate import LINEAGE,load
from render_profile import page,diagram,link,source_link,esc
from render_readme_section import block,splice

ROOT=LINEAGE.parent

def full_map(data):
    nodes,edges=data['nodes'],data['edges']
    lines=['<!-- Generated by lineage/render.py; edit lineage.yaml. -->','# Public repository lineage','',
           f"Observed {data['observed']}. {len(nodes)} public repositories. Private repositories are outside this projection.",'',
           'A source inspection proves that cited bytes exist at a revision. It does not prove the prose is true, that a runtime works, or that a documented integration is implemented. Earlier test observations remain attributed history.','',
           '## Relation semantics','',
           '`A supersedes B` means A replaced B as an active line. `A may-provide-substrate B` means B documents A as an optional provider. `A references B` records a source citation. `sibling-phase` is a comparison; it does not establish chronology.','',
           'The original relation vocabulary remains supported. `may-provide-substrate` preserves optionality; `references` preserves citation without asserting dependency. These extensions were required by the source evidence.','',diagram(nodes,edges),'',
           '## Evidence for relations','']
    for e in edges:
        lines += [f"### {e['from']} → {e['to']} · {e['type']} · {e['state']}",'',e['evidence'],'',f"Limit: {e['limit']}",'']
        for s in e['sources']:
            n=nodes[s['node']];url=f"https://github.com/{n['repo']}/blob/{s['revision']}/{s['path']}"
            lines += [f"- [{s['node']} / {s['path']}]({url}) — `{s['sha256']}`",f"  Source text: {esc(s['quote'])}"]
        lines.append('')
    lines += ['## Repository observations','']
    for name,n in nodes.items():
        ev=n['evidence'];lines += [f"### {link(n)}",'',n['claim'],'',f"Source: {source_link(n)}. Observed {ev['observed']}.",'','```sh',ev['command'],'```','',ev['result'],'']
        if n.get('upstream'):lines += [f"Upstream: [{n['upstream']}](https://github.com/{n['upstream']}).",'']
        if n.get('status_basis'):lines += [n['status_basis'],'']
        lines += [n['unconnected_reason'],'']
        if n.get('reported_evidence'):
            past=n['reported_evidence'];lines += [f"Earlier report ({past['observed']}): `{past['command']}` → {past['result']}. {past['attribution']}",'']
    lines += ['## Unsubstantiated proposals','',
              'The inspection did not establish holon → ontum, holon → Soveraeign, Soveraeign → ontum, familiar → HowDo, Agentic → Soveraeign, or small-world → Diedle. Generic instrument capability in DDD-CCC, context, evident, and system-cartographer does not identify a particular repository being instrumented. These are discovery questions, not graph edges.','',
              'See [WORK-QUEUE.md](WORK-QUEUE.md) for the bounded continuation.','']
    return '\n'.join(lines)

def schematic(data):
    """Use generic Components/Paths as a presentation of the existing record."""
    nodes=data['nodes']; components=[];wires=[]
    for i,(name,node) in enumerate(nodes.items()):
        components.append({'id':'repo:'+name,'type':'hold','x':180+(i%4)*340,'y':160+(i//4)*210,
          'config':{'label':node['repo'].split('/')[1], 'signalMode':'passive',
          'presentation':{'size':{'w':230,'h':120},'text':node['claim']+'\n'+node['repo'],'internalLayout':'text-only'},
          'ports':{'in':{'side':'left','face':'external','flow':'in'},'out':{'side':'right','face':'external','flow':'out'}}}})
    for i,e in enumerate(data['edges']):
        if e['state']=='unsupported': continue
        wires.append({'id':f'relation:{i}','a':'repo:'+e['from'],'b':'repo:'+e['to'],'aSide':'out','bSide':'in',
          'config':{'direction':'forward','label':e['type']+' ['+e['state']+']'},'editor':{'rate':0}})
    return json.dumps({'schema':'soveraeign.schematic/document@0.1','id':'public-repository-lineage','revision':0,
        'meta':{'title':'Public repository lineage','description':'Generated presentation. Edge labels retain evidence state. No runtime integration or permission is implied.'},
        'components':components,'wires':wires,'references':[],'layout':{}},ensure_ascii=False,indent=2)+'\n'

def outputs(data):
    nodes,edges=data['nodes'],data['edges']
    generated={ROOT/'profile-README.md':page(nodes,edges),ROOT/'LINEAGE.md':full_map(data),ROOT/'lineage.sov':schematic(data)}
    metadata=subprocess.check_output([sys.executable,str(ROOT/'render_repo_metadata.py')],text=True)
    generated[ROOT/'repo-metadata.sh']=metadata
    readme=ROOT.parent/'README.md'
    generated[readme]=splice(readme.read_text(),block('system-cartographer',nodes,edges))
    return generated

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    data=load(LINEAGE.read_text()); files=outputs(data);drift=[]
    for path,text in files.items():
        if args.check:
            if not path.exists() or path.read_text()!=text:drift.append(str(path.relative_to(ROOT.parent)))
        else:path.write_text(text,encoding='utf-8',newline='\n')
    if drift:print('FAIL: generated drift: '+', '.join(drift));return 1
    print(f'PASS: {len(files)} generated projections '+('match' if args.check else 'written'));return 0
if __name__=='__main__':raise SystemExit(main())
