# Generated from lineage.yaml. Do not hand-edit; re-run the renderer.
# Requires `gh` authenticated as the repository owner.

gh repo edit bdf1992/baseless --description 'An empty repository. The name is reserved and nothing has been committed to it.' --add-topic placeholder
gh repo edit bdf1992/Canvas --description 'Arranges addressable things in space, relates them visibly, and wires a subset into executable circuits.' --add-topic spatial-composition --add-topic canvas --add-topic wiring --add-topic addressable-objects --add-topic python
gh repo edit bdf1992/context --description 'A single-file harness that installs into any directory and gives an agent a bounded world to work in.' --add-topic llm-agents --add-topic context-management --add-topic single-file --add-topic harness --add-topic bootstrap
gh repo edit bdf1992/DDD-CCC --description 'Measures how much of a repository'"'"'s meaning is actually covered by its tests, and names the gaps.' --add-topic test-coverage --add-topic semantic-coverage --add-topic mutation-testing --add-topic static-analysis --add-topic python
gh repo edit bdf1992/evident --description 'A session-based instrument for bootstrapping how an organization works, in about thirty minutes.' --add-topic organizational-design --add-topic bootstrap --add-topic ai-native --add-topic session-based
gh repo edit bdf1992/familiar --description 'A local-first workbench for agent guidance that a practitioner has to accept before it binds.' --add-topic agent-guidance --add-topic local-first --add-topic workbench --add-topic portable-agents --add-topic python
gh repo edit bdf1992/holon --description 'An archived notebook on whether one generative distinction could account for structure and form.' --add-topic research --add-topic archive --add-topic notes --add-topic formal-systems
gh repo edit bdf1992/HowDo --description 'A discipline for understanding a problem before acting on it.' --add-topic methodology --add-topic discipline --add-topic understanding-before-acting --add-topic python
gh repo edit bdf1992/ide --description 'A small in-chat editor that opens in a side panel and reuses proven browser components.' --add-topic editor --add-topic chatgpt --add-topic browser --add-topic side-panel --add-topic javascript
gh repo edit bdf1992/LangWorld --description 'An unmodified copy of LangChain'"'"'s react-agent template. None of the code is the owner'"'"'s.' --add-topic template --add-topic langgraph --add-topic third-party-copy --add-topic reference
gh repo edit bdf1992/nostalgia --description 'An agent-assisted helper for getting classic games running and playable with others.' --add-topic retro-gaming --add-topic emulation --add-topic multiplayer --add-topic compatibility --add-topic agent-assisted
gh repo edit bdf1992/ontum --description 'A governed gateway for autonomous AI work, where the append-only log is the truth and every other view is folded from it.' --add-topic ai-native --add-topic append-only-log --add-topic agent-governance --add-topic autonomous-agents --add-topic provenance --add-topic python
gh repo edit bdf1992/Owl --description 'Turns a rough ask into a complete inspectable attempt early, then redraws it from feedback.' --add-topic methodology --add-topic prototyping --add-topic claude-code --add-topic skill --add-topic iteration
gh repo edit bdf1992/S4 --description 'Tests whether the two-axis split between programs and protocols survives being handed to a fresh agent.' --add-topic protocol --add-topic experiment --add-topic agent-harness --add-topic claude-code --add-topic subprotocol
gh repo edit bdf1992/schematically --description 'A schematic editor whose document is a semantic model of components, parts and wires rather than a drawing.' --add-topic schematic-editor --add-topic semantic-model --add-topic svg --add-topic mcp --add-topic ai-native --add-topic browser --add-topic javascript
gh repo edit bdf1992/small-world --description 'A bounded lab for generative-world architecture, built for Catalyst Core.' --add-topic generative-worlds --add-topic architecture --add-topic catalyst-core --add-topic javascript --add-topic simulation
gh repo edit bdf1992/Soveraeign --description 'People and AI models work through the same records, permissions and history.' --add-topic local-first --add-topic ai-native --add-topic provenance --add-topic audit-log --add-topic permissions --add-topic records --add-topic python
gh repo edit bdf1992/system-cartographer --description 'Reverse-engineers an undocumented agent or AI-native system into a description complete enough to rebuild it.' --add-topic claude-code --add-topic skill --add-topic reverse-engineering --add-topic documentation --add-topic ai-native --add-topic lineage

# Archived on GitHub. These are rejected until the repository is
# unarchived, so they are commented out rather than left to fail.
# gh repo edit bdf1992/Agentic --description 'Spawned and scheduled real Claude Code sessions from a dashboard, each configured for a role.' --add-topic multi-agent --add-topic claude-code --add-topic dashboard --add-topic orchestration --add-topic archive
# gh repo edit bdf1992/onton --description 'Types how a generated artifact was formed, so trust carries across human, machine and composed work.' --add-topic provenance --add-topic type-system --add-topic ai-native --add-topic artifact-provenance --add-topic receipts --add-topic python
