#!/usr/bin/env bash
# Generated by lineage/render.py. Default is a plan; --apply performs the edits.
set -euo pipefail
apply=false
if [[ "${1:-}" == "--apply" ]]; then apply=true
elif [[ $# -gt 0 ]]; then printf 'usage: %s [--apply]\n' "$0"; exit 2; fi

reconcile() {
  local repo="$1" description="$2" topics="$3" payload="$4" current_desc current_topics state
  state="$(gh api "repos/$repo" --jq '[.visibility, (.archived|tostring)] | join(" ")')"
  if [[ "$state" != 'public false' ]]; then
    printf 'skip %s: visibility/archive state changed (%s)\n' "$repo" "$state"
    return
  fi
  current_desc="$(gh repo view "$repo" --json description --jq '.description // ""')"
  current_topics="$(gh api "repos/$repo/topics" --jq '.names | sort | join(" ")')"
  if [[ "$current_desc" != "$description" ]]; then
    printf '%s description: %s -> %s\n' "$repo" "$current_desc" "$description"
    if $apply; then gh repo edit "$repo" --description "$description"; fi
  fi
  if [[ "$current_topics" != "$topics" ]]; then
    printf '%s topics: %s -> %s\n' "$repo" "$current_topics" "$topics"
    if $apply; then gh api --method PUT "repos/$repo/topics" --input - <<< "$payload" >/dev/null; fi
  fi
}

reconcile bdf1992/AntSimulator 'A reference fork of a C++ ant simulation.' 'cpp reference simulation' '{"names": ["cpp", "reference", "simulation"]}'
reconcile bdf1992/baseless 'A reserved repository name with a placeholder README and license.' placeholder '{"names": ["placeholder"]}'
reconcile bdf1992/Canvas 'Arranges addressable things in space, relates them visibly, and wires a subset into executable circuits.' 'addressable-objects canvas python spatial-composition wiring' '{"names": ["addressable-objects", "canvas", "python", "spatial-composition", "wiring"]}'
reconcile bdf1992/Clouds 'A reference fork of a Unity cloud raymarching experiment.' 'raymarching reference unity' '{"names": ["raymarching", "reference", "unity"]}'
reconcile bdf1992/context 'A single-file harness that installs into any directory and gives an agent a bounded world to work in.' 'bootstrap context-management harness llm-agents single-file' '{"names": ["bootstrap", "context-management", "harness", "llm-agents", "single-file"]}'
reconcile bdf1992/DDD-CCC 'A typed measurement framework that records claims about repositories and checks declared module proofs.' 'mutation-testing python semantic-coverage static-analysis test-coverage' '{"names": ["mutation-testing", "python", "semantic-coverage", "static-analysis", "test-coverage"]}'
reconcile bdf1992/Diedle 'An idle dice game implemented in Unity on the Omega mathematical model.' 'dice game unity' '{"names": ["dice", "game", "unity"]}'
reconcile bdf1992/digitaldimensions 'A reference fork containing a browser dimensional incremental game.' 'browser game reference' '{"names": ["browser", "game", "reference"]}'
reconcile bdf1992/Drew-s-Campfire-Videos 'A reference fork of Manim and Blender animation source for Drew’s Campfire.' 'animation manim reference' '{"names": ["animation", "manim", "reference"]}'
reconcile bdf1992/evident 'A session-based instrument for bootstrapping how an organization works, in about thirty minutes.' 'ai-native bootstrap organizational-design session-based' '{"names": ["ai-native", "bootstrap", "organizational-design", "session-based"]}'
reconcile bdf1992/familiar 'A local-first experimental workbench for portable agent guidance and evidence-backed skill evolution.' 'agent-guidance local-first portable-agents python workbench' '{"names": ["agent-guidance", "local-first", "portable-agents", "python", "workbench"]}'
reconcile bdf1992/field 'A reference fork of Microsoft Code - OSS.' 'editor reference' '{"names": ["editor", "reference"]}'
reconcile bdf1992/Fluid-Sim 'A reference fork of a Unity fluid simulation.' 'reference simulation unity' '{"names": ["reference", "simulation", "unity"]}'
reconcile bdf1992/holon 'A research notebook exploring generative distinctions, structure, and form.' 'archive formal-systems notes research' '{"names": ["archive", "formal-systems", "notes", "research"]}'
reconcile bdf1992/HowDo 'A discipline for understanding a problem before acting on it.' 'discipline methodology python understanding-before-acting' '{"names": ["discipline", "methodology", "python", "understanding-before-acting"]}'
reconcile bdf1992/ide 'A small in-chat editor that opens in a side panel and reuses proven browser components.' 'browser chatgpt editor javascript side-panel' '{"names": ["browser", "chatgpt", "editor", "javascript", "side-panel"]}'
reconcile bdf1992/LangWorld 'A copy of the LangChain ReAct agent template, retained as a reference.' 'langgraph reference template third-party-copy' '{"names": ["langgraph", "reference", "template", "third-party-copy"]}'
reconcile bdf1992/nostalgia 'An agent-assisted helper for getting classic games running and playable with others.' 'agent-assisted compatibility emulation multiplayer retro-gaming' '{"names": ["agent-assisted", "compatibility", "emulation", "multiplayer", "retro-gaming"]}'
reconcile bdf1992/ontum 'A governed gateway for autonomous AI work, where the append-only log is the truth and every other view is folded from it.' 'agent-governance ai-native append-only-log autonomous-agents provenance python' '{"names": ["agent-governance", "ai-native", "append-only-log", "autonomous-agents", "provenance", "python"]}'
reconcile bdf1992/Owl 'Turns a rough request or exploratory mark into a complete, inspectable result, then redraws that same target from feedback without drifting into another project.' 'claude-code iteration methodology prototyping skill' '{"names": ["claude-code", "iteration", "methodology", "prototyping", "skill"]}'
reconcile bdf1992/S4 'Tests whether the two-axis split between programs and protocols survives being handed to a fresh agent.' 'agent-harness claude-code experiment protocol subprotocol' '{"names": ["agent-harness", "claude-code", "experiment", "protocol", "subprotocol"]}'
reconcile bdf1992/schematically 'A schematic editor whose document is a semantic model of components, parts and wires rather than a drawing.' 'ai-native browser javascript mcp schematic-editor semantic-model svg' '{"names": ["ai-native", "browser", "javascript", "mcp", "schematic-editor", "semantic-model", "svg"]}'
reconcile bdf1992/Slime-Simulation 'A reference fork of a Unity slime simulation.' 'reference simulation unity' '{"names": ["reference", "simulation", "unity"]}'
reconcile bdf1992/small-world 'A bounded lab for generative-world architecture, built for Catalyst Core.' 'architecture catalyst-core generative-worlds javascript simulation' '{"names": ["architecture", "catalyst-core", "generative-worlds", "javascript", "simulation"]}'
reconcile bdf1992/Soveraeign 'People and AI models work through the same records, permissions and history.' 'ai-native audit-log local-first permissions provenance python records' '{"names": ["ai-native", "audit-log", "local-first", "permissions", "provenance", "python", "records"]}'
reconcile bdf1992/StableIndexVector 'A reference fork of a C++ vector container with stable element identifiers.' 'cpp data-structures reference' '{"names": ["cpp", "data-structures", "reference"]}'
reconcile bdf1992/system-cartographer 'A Claude Code skill that reverse-engineers an undocumented agent or AI-native system into a description complete enough to rebuild it.' 'ai-native claude-code documentation lineage reverse-engineering skill' '{"names": ["ai-native", "claude-code", "documentation", "lineage", "reverse-engineering", "skill"]}'

# Archived at the recorded observation; do not unarchive from this projection.
# reconcile bdf1992/Agentic 'Spawned and scheduled real Claude Code sessions from a dashboard, each configured for a role.' 'archive claude-code dashboard multi-agent orchestration' '{"names": ["archive", "claude-code", "dashboard", "multi-agent", "orchestration"]}'
# reconcile bdf1992/onton 'Types how a generated artifact was formed, so trust carries across human, machine and composed work.' 'ai-native artifact-provenance provenance python receipts type-system' '{"names": ["ai-native", "artifact-provenance", "provenance", "python", "receipts", "type-system"]}'
